# Generated by Django 5.2.8 on 2025-11-10 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('yield_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], default='GROWING', max_length=20)),
            ],
        ),
    ]
