# Generated by Django 5.2.8 on 2025-11-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fan_on', models.BooleanField(default=True)),
                ('fan_auto', models.BooleanField(default=True)),
                ('fan_value', models.IntegerField(default=35)),
                ('humidifier_on', models.BooleanField(default=True)),
                ('humidifier_auto', models.BooleanField(default=True)),
                ('humidifier_value', models.IntegerField(default=85)),
                ('heater_on', models.BooleanField(default=True)),
                ('heater_auto', models.BooleanField(default=True)),
                ('heater_value', models.IntegerField(default=22)),
                ('co2_on', models.BooleanField(default=True)),
                ('co2_auto', models.BooleanField(default=True)),
                ('co2_value', models.IntegerField(default=900)),
                ('lights_on', models.BooleanField(default=True)),
                ('lights_auto', models.BooleanField(default=True)),
                ('lights_value', models.IntegerField(default=50)),
            ],
        ),
    ]
