# Generated by Django 5.2.8 on 2025-11-10 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_environmentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this batch', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
