# Generated by Django 5.2.8 on 2025-11-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productionbatch_cost_productionbatch_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='predicted_yield_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ML predicted yield', max_digits=5, null=True),
        ),
    ]
