# Generated by Django 5.2.8 on 2025-11-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productionbatch_predicted_yield_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('HUMIDIFIER_ON', 'Humidifier Activated'), ('HUMIDIFIER_OFF', 'Humidifier Deactivated'), ('VENTILATION_ON', 'Ventilation Activated'), ('VENTILATION_OFF', 'Ventilation Deactivated'), ('HEATER_ON', 'Heater Activated'), ('HEATER_OFF', 'Heater Deactivated')], max_length=20)),
                ('reason', models.TextField(help_text='Why this action was taken')),
                ('temperature_before', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity_before', models.DecimalField(decimal_places=1, max_digits=4)),
                ('co2_before', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Model confidence percentage', max_digits=5)),
                ('was_effective', models.BooleanField(blank=True, help_text='Did this prevent a warning?', null=True)),
            ],
        ),
    ]
