# Generated by Django 5.2.8 on 2025-11-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_automationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Uploaded mushroom image", upload_to="disease_images/"
                    ),
                ),
                (
                    "detected_disease",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("green_mold", "Green Mold (Trichoderma)"),
                            ("bacterial_blotch", "Bacterial Blotch"),
                            ("cobweb", "Cobweb Disease"),
                            ("dry_bubble", "Dry Bubble"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Model confidence percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("treatment_recommendation", models.TextField(blank=True)),
                ("prevention_tips", models.TextField(blank=True)),
                (
                    "action_taken",
                    models.TextField(
                        blank=True,
                        help_text="What action was taken to address the issue",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Has the issue been resolved?"
                    ),
                ),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated production batch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.productionbatch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease Detection",
                "verbose_name_plural": "Disease Detections",
                "ordering": ["-timestamp"],
            },
        ),
    ]
