# Generated by Django 5.2.8 on 2025-12-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_order_product_description_product_is_active_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `core_orderitem` (
                `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                `order_id` bigint NOT NULL,
                `product_id` bigint NOT NULL,
                `quantity_kg` decimal(5,1) NOT NULL,
                `price_per_kg` decimal(6,2) NOT NULL,
                `subtotal` decimal(10,2) NOT NULL,
                FOREIGN KEY (`order_id`) REFERENCES `core_order` (`id`),
                FOREIGN KEY (`product_id`) REFERENCES `core_product` (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """,
            reverse_sql="DROP TABLE IF EXISTS `core_orderitem`;"
        ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS `core_cartitem` (
                `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                `cart_id` bigint NOT NULL,
                `product_id` bigint NOT NULL,
                `quantity_kg` decimal(5,1) NOT NULL,
                UNIQUE KEY `core_cartitem_cart_id_product_id_unique` (`cart_id`, `product_id`),
                FOREIGN KEY (`cart_id`) REFERENCES `core_cart` (`id`),
                FOREIGN KEY (`product_id`) REFERENCES `core_product` (`id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """,
            reverse_sql="DROP TABLE IF EXISTS `core_cartitem`;"
        ),
    ]
