# Generated by Django 5.2.8 on 2026-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_air_quality_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="core_sensor_timesta_590409_idx",
            old_name="core_sensor_timesta_idx",
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="fan_air_quality_threshold",
            field=models.IntegerField(
                default=600,
                help_text="Air quality threshold PPM - fan turns ON if exceeded",
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="fan_humidity_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=95.0,
                help_text="Humidity threshold % - fan turns ON if exceeded",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="fan_temp_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=30.0,
                help_text="Temperature threshold in °C - fan turns ON if exceeded",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="heater_high_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=20.0,
                help_text="Temperature threshold °C - heater turns OFF if above",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="heater_low_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=15.0,
                help_text="Temperature threshold °C - heater turns ON if below",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="humidifier_high_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=90.0,
                help_text="Humidity threshold % - humidifier turns OFF if above",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="humidifier_low_threshold",
            field=models.DecimalField(
                decimal_places=1,
                default=75.0,
                help_text="Humidity threshold % - humidifier turns ON if below",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="hysteresis_margin",
            field=models.DecimalField(
                decimal_places=1,
                default=2.0,
                help_text="Margin to prevent rapid ON/OFF cycling",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="environmentsettings",
            name="last_automation_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="co2_auto",
            field=models.BooleanField(
                default=True, help_text="Enable automatic control"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="co2_on",
            field=models.BooleanField(
                default=False, help_text="Current CO2 injector state"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="co2_value",
            field=models.IntegerField(default=900, help_text="Target CO2 PPM"),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="fan_auto",
            field=models.BooleanField(
                default=True, help_text="Enable automatic control based on sensors"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="fan_on",
            field=models.BooleanField(
                default=False, help_text="Current fan state (ON/OFF)"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="fan_value",
            field=models.IntegerField(
                default=35, help_text="Fan speed percentage target"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="heater_auto",
            field=models.BooleanField(
                default=True, help_text="Enable automatic control"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="heater_on",
            field=models.BooleanField(default=False, help_text="Current heater state"),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="heater_value",
            field=models.IntegerField(default=22, help_text="Target temperature"),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="humidifier_auto",
            field=models.BooleanField(
                default=True, help_text="Enable automatic control"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="humidifier_on",
            field=models.BooleanField(
                default=False, help_text="Current humidifier state"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="humidifier_value",
            field=models.IntegerField(
                default=85, help_text="Target humidity percentage"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="lights_auto",
            field=models.BooleanField(
                default=True, help_text="Enable automatic control"
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="lights_on",
            field=models.BooleanField(default=False, help_text="Current lights state"),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="lights_value",
            field=models.IntegerField(
                default=50, help_text="Light intensity percentage"
            ),
        ),
    ]
