# Generated by Django 5.2.8 on 2026-02-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_automation_thresholds"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "store_name",
                    models.CharField(default="KABUTOMATE Farm", max_length=200),
                ),
                (
                    "store_address",
                    models.TextField(blank=True, help_text="Store physical address"),
                ),
                (
                    "store_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Store latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "store_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Store longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "base_shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Base shipping fee in currency",
                        max_digits=6,
                    ),
                ),
                (
                    "fee_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Additional fee per kilometer",
                        max_digits=6,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        help_text="Order total above this amount gets free shipping",
                        max_digits=8,
                    ),
                ),
                (
                    "max_delivery_distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Maximum delivery distance in kilometers",
                        max_digits=6,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
