# Generated by Django 5.2.8 on 2026-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_storesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Customer delivery location latitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Customer delivery location longitude",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="fan_value",
            field=models.IntegerField(
                default=25,
                help_text="Target temperature °C - fan turns ON above this, OFF below",
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="heater_value",
            field=models.IntegerField(
                default=22,
                help_text="Target temperature °C - heater runs until this is reached",
            ),
        ),
        migrations.AlterField(
            model_name="environmentsettings",
            name="humidifier_value",
            field=models.IntegerField(
                default=85,
                help_text="Target humidity % - humidifier runs until this is reached",
            ),
        ),
    ]
