# Generated by Django 5.2.8 on 2026-02-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_add_customer_coordinates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productreview",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Order this review is linked to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="core.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user", "order")},
        ),
    ]
