# Generated by Django 5.2.8 on 2026-02-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_order_based_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("fresh", "Fresh Mushrooms"),
                    ("cooked", "Cooked / Ready-to-Eat"),
                ],
                default="fresh",
                help_text="Type of product",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="batch_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Published - visible for sale in e-commerce"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price per kilogram (or per unit for cooked products)",
                max_digits=6,
            ),
        ),
    ]
