# Generated by Django 5.2.8 on 2026-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, help_text="When payment was confirmed", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Payment reference number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Unpaid"),
                    ("PENDING", "Payment Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Payment Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="UNPAID",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Payment gateway transaction ID",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("COD", "Cash on Delivery"), ("GCASH", "GCash")],
                default="COD",
                max_length=50,
            ),
        ),
    ]
