# Generated by Django 5.2.8 on 2026-03-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_gcash_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")],
                        default="IMAGE",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="review_media/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail for videos",
                        null=True,
                        upload_to="review_media/thumbnails/",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(default=0, help_text="File size in bytes"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True, help_text="Admin can hide inappropriate media"
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.productreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Media",
                "verbose_name_plural": "Review Media",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
