# Generated by Django 5.2.8 on 2026-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_review_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storesettings",
            name="base_shipping_fee",
        ),
        migrations.AddField(
            model_name="storesettings",
            name="minimum_base_distance_km",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                help_text="Distance in km covered by the minimum base fee",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="minimum_base_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Minimum delivery fee for the first X km",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=300.0,
                help_text="Minimum order amount required to place an order",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="storesettings",
            name="fee_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Additional fee per kilometer beyond base distance",
                max_digits=6,
            ),
        ),
    ]
