# Generated by Django 5.2.8 on 2026-03-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_store_delivery_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Calories per serving",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="carbohydrates",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Carbohydrates in grams",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Fat in grams",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fiber",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Fiber in grams",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Protein in grams",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="serving_size",
            field=models.CharField(
                blank=True,
                default="100g",
                help_text="Serving size (e.g., 100g, 1 cup)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sodium",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Sodium in milligrams",
                max_digits=6,
                null=True,
            ),
        ),
    ]
