# Generated by Django 5.2.8 on 2026-04-26

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_product_unit_and_fruit_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_proof_image',
            field=models.ImageField(
                blank=True,
                help_text='Customer-uploaded screenshot proof for manual GCash payment',
                null=True,
                upload_to=core.models.payment_proof_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gcash_qr_code',
            field=models.ImageField(
                blank=True,
                help_text='Admin-uploaded GCash QR code used for manual checkout payments',
                null=True,
                upload_to=core.models.gcash_qr_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                choices=[('COD', 'Cash on Delivery'), ('GCASH', 'GCash (Manual)')],
                default='COD',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PENDING_VERIFICATION', 'Pending Verification'),
                    ('PROCESSING', 'Processing'),
                    ('SHIPPED', 'Shipped'),
                    ('DELIVERED', 'Delivered'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
